apiVersion: v1
kind: Service
metadata:
  name: simple-go-app-service
  labels:
    app: simple-go-app
spec:
  selector:
    app: simple-go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort